/**
 * @file adc.c
 * @brief ADC configuration and control for STM32G031 microcontroller.
 *
 * This module implements the ADC driver for the STM32G031, providing
 * initialization, calibration, and data acquisition functionalities.
 * It supports single-shunt current sensing and other analog measurements
 * required for motor control applications.
 *
 * The driver is designed to work with timer-triggered conversions to ensure
 * precise synchronization with PWM signals, which is critical for accurate
 * current reconstruction in FOC algorithms.
 *
 * Features:
 * - ADC initialization and calibration sequence
 * - Configurable channel selection and sampling time
 * - Timer-triggered conversion support (e.g., synchronized with PWM)
 * - Interrupt-based end-of-conversion handling
 * - Optional DMA support for efficient data transfer
 *
 * @note
 * This configuration is tailored for the EVS32 motor control board,
 * where the ADC is primarily used for single-shunt current measurement
 * and DC bus voltage sensing.
 *
 * @warning
 * Incorrect trigger configuration or sampling time may lead to
 * distorted current measurements, directly affecting control stability.
 *
 * @author
 * Jesus Daniel Britoloaiza
 *
 * @copyright
 * Copyright (c) 2026 Jesus Daniel Britoloaiza
 *
 * @license
 * This source code is provided for educational and research purposes.
 */


 /**
 * @brief Starts ADC conversion synchronized with PWM timer.
 *
 * Enables the ADC and configures it to start conversions based on
 * a hardware trigger generated by the PWM timer (e.g., TIM1).
 *
 * This function is intended for time-critical applications such as
 * motor control, where ADC sampling must be precisely aligned with
 * the PWM switching cycle to ensure accurate current measurements.
 *
 * The trigger source must be preconfigured to a timer event
 * (e.g., TIM1 TRGO or compare event) that occurs within a valid
 * sampling window (typically in the middle of the PWM period).
 *
 * @note
 * The ADC must be initialized and calibrated before calling this function.
 *
 * @warning
 * Incorrect trigger timing may result in sampling during switching noise,
 * leading to inaccurate current reconstruction in single-shunt topologies.
 */
void vADC_StartPWMTrigger(void);



void vADC_Init(void)
{
    /* 1. Enable ADC clock - this is in rcc.c file*/

    /* 2. Enable GPIO analog pins (ejemplo: PA0 = ADC_IN0) */

    /* 3. Disable ADC before configuration */

    /* 4. Configure ADC clock (asynchronous or synchronous) */

    /* 5. Resolution (12-bit) */

    /* 6. Data alignment (right) */

    /* 7. External trigger */

    /* 8. Sampling time  */

    /* 9. Select channel */

    /* 10. Single conversion mode (no continuous) */

    /* 11. Clear ADRDY flag */
}