#include "pwm.h"
#include "stm32g031xx.h"

void PWM_Init(void)
{
  // Enable TIM1 clock
  RCC->APBENR2 |= RCC_APBENR2_TIM1EN;

  // Configure GPIO for TIM1 PWM
  RCC->IOPENR |= RCC_IOPENR_GPIOAEN | RCC_IOPENR_GPIOBEN;
  GPIOA->MODER &= ~(GPIO_MODER_MODE7 | GPIO_MODER_MODE8 | GPIO_MODER_MODE9 | GPIO_MODER_MODE10);
  GPIOA->MODER |= GPIO_MODER_MODE7_1 | GPIO_MODER_MODE8_1 | GPIO_MODER_MODE9_1 | GPIO_MODER_MODE10_1;
  GPIOB->MODER &= ~(GPIO_MODER_MODE0 | GPIO_MODER_MODE1);
  GPIOB->MODER |= GPIO_MODER_MODE0_1 | GPIO_MODER_MODE1_1;
  GPIOA->AFR[0] |= (6 << GPIO_AFRL_AFSEL7_Pos);
  GPIOA->AFR[1] |= (2 << GPIO_AFRH_AFSEL8_Pos) | (2 << GPIO_AFRH_AFSEL9_Pos) | (2 << GPIO_AFRH_AFSEL10_Pos);
  GPIOB->AFR[0] |= (2 << GPIO_AFRL_AFSEL0_Pos) | (2 << GPIO_AFRL_AFSEL1_Pos);

  // Configure TIM1
  TIM1->CR1 = 0;
  TIM1->CR2 = 0;
  TIM1->SMCR = 0;
  TIM1->DIER = 0;
  TIM1->PSC = 0;
  TIM1->ARR = 20000;
  TIM1->RCR = 0;
  TIM1->CCR1 = 1000;
  TIM1->CCR2 = 0;
  TIM1->CCR3 = 0;
  TIM1->CCMR1 = TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1PE | TIM_CCMR1_OC1FE | TIM_CCMR1_OC2M_2 | TIM_CCMR1_OC2M_1 | TIM_CCMR1_OC2PE | TIM_CCMR1_OC2FE;
  TIM1->CCMR2 = TIM_CCMR2_OC3M_2 | TIM_CCMR2_OC3M_1 | TIM_CCMR2_OC3PE | TIM_CCMR2_OC3FE;
  TIM1->CCMR3 = 0;
  TIM1->CCER = TIM_CCER_CC1E | TIM_CCER_CC1NE | TIM_CCER_CC2E | TIM_CCER_CC2NE | TIM_CCER_CC3E | TIM_CCER_CC3NE;
  TIM1->CNT = 0;
  TIM1->BDTR = 0x200a0ff;
  TIM1->DCR = 0;
  TIM1->DMAR = 0;
  TIM1->CR1 |= 0x1d1;
  TIM1->EGR = TIM_EGR_UG;
}

void PWM_Start(void)
{
  TIM1->CR1 |= TIM_CR1_CEN;
}

void PWM_UpdatePhaseCompare(uint32_t compareA, uint32_t compareB, uint32_t compareC)
{
  TIM1->CCR1 = compareA;
  TIM1->CCR2 = compareB;
  TIM1->CCR3 = compareC;
}
void PWM_CHANNEL1_SET_CYCLEDUTY(uint32_t ui32DutyCycle){
	TIM1->CCR1 = ui32DutyCycle;
}
void PWM_CHANNEL2_SET_CYCLEDUTY(uint32_t ui32DutyCycle){
	TIM1->CCR2 = ui32DutyCycle;
}
void PWM_CHANNEL3_SET_CYCLEDUTY(uint32_t ui32DutyCycle){
	TIM1->CCR3 = ui32DutyCycle;
}
