/**
 * @file rcc.h
 * @brief RCC register bitfield macros for STM32G031
 * @author Jesus Daniel Britoloaiza
 */

#include "stm32g031xx.h"
#include "stm32g0xx.h"

/*macros general */
#define dOn 1U
#define dOff 0U
/* IO port clock enable register */
#define dRCC_IOPENR_GPIOA_MASK      0x00000001U
#define dRCC_IOPENR_GPIOASHIFT      0U
#define dRCC_IOPENR_GPIOAEN(x)    (((uint32_t)(((uint32_t)(x)) << dRCC_IOPENR_GPIOASHIFT)) & dRCC_IOPENR_GPIOA_MASK)
#define dRCC_IOPENR_GPIOB_MASK      0x00000002U
#define dRCC_IOPENR_GPIOBSHIFT      1U
#define dRCC_IOPENR_GPIOBEN(x)    (((uint32_t)(((uint32_t)(x)) << dRCC_IOPENR_GPIOBSHIFT)) & dRCC_IOPENR_GPIOB_MASK)
#define dRCC_IOPENR_GPIOC_MASK      0x00000004U
#define dRCC_IOPENR_GPIOCSHIFT      2U
#define dRCC_IOPENR_GPIOCEN(x)    (((uint32_t)(((uint32_t)(x)) << dRCC_IOPENR_GPIOCSHIFT)) & dRCC_IOPENR_GPIOC_MASK)
#define dRCC_IOPENR_GPIOD_MASK      0x00000008U
#define dRCC_IOPENR_GPIODSHIFT      3U
#define dRCC_IOPENR_GPIODEN(x)    (((uint32_t)(((uint32_t)(x)) << dRCC_IOPENR_GPIODSHIFT)) & dRCC_IOPENR_GPIOD_MASK)
#define dRCC_IOPENR_GPIOE_MASK      0x00000010U
#define dRCC_IOPENR_GPIOESHIFT      4U
#define dRCC_IOPENR_GPIOEEN(x)    (((uint32_t)(((uint32_t)(x)) << dRCC_IOPENR_GPIOESHIFT)) & dRCC_IOPENR_GPIOE_MASK)
#define dRCC_IOPENR_GPIOF_MASK      0x00000020U
#define dRCC_IOPENR_GPIOFSHIFT      5U
#define dRCC_IOPENR_GPIOFEN(x)    (((uint32_t)(((uint32_t)(x)) << dRCC_IOPENR_GPIOFSHIFT)) & dRCC_IOPENR_GPIOF_MASK)

/* AHB peripheral clock enable register */
#define dRCC_AHBENR_DMA1_MASK      0x00000001U
#define dRCC_AHBENR_DMA1SHIFT      0U
#define dRCC_AHBENR_DMA1EN(x)      (((uint32_t)(((uint32_t)(x)) << dRCC_AHBENR_DMA1SHIFT)) & dRCC_AHBENR_DMA1_MASK)
#define dRCC_AHBENR_DMA2_MASK      0x00000002U
#define dRCC_AHBENR_DMA2SHIFT      1U
#define dRCC_AHBENR_DMA2EN(x)      (((uint32_t)(((uint32_t)(x)) << dRCC_AHBENR_DMA2SHIFT)) & dRCC_AHBENR_DMA2_MASK)
#define dRCC_AHBENR_FLASH_MASK     0x00000100U
#define dRCC_AHBENR_FLASHSHIFT     8U
#define dRCC_AHBENR_FLASHEN(x)     (((uint32_t)(((uint32_t)(x)) << dRCC_AHBENR_FLASHSHIFT)) & dRCC_AHBENR_FLASH_MASK)
#define dRCC_AHBENR_CRC_MASK       0x00001000U
#define dRCC_AHBENR_CRCSHIFT       12U
#define dRCC_AHBENR_CRCEN(x)       (((uint32_t)(((uint32_t)(x)) << dRCC_AHBENR_CRCSHIFT)) & dRCC_AHBENR_CRC_MASK)

/* APB peripheral clock enable register */
#define dRCC_APBENR1_TIM2_MASK     0x00000001U
#define dRCC_APBENR1_TIM2SHIFT     0U
#define dRCC_APBENR1_TIM2EN(x)     (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR1_TIM2SHIFT)) & dRCC_APBENR1_TIM2_MASK)
#define dRCC_APBENR1_TIM3_MASK     0x00000002U
#define dRCC_APBENR1_TIM3SHIFT     1U
#define dRCC_APBENR1_TIM3EN(x)     (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR1_TIM3SHIFT)) & dRCC_APBENR1_TIM3_MASK)
#define dRCC_APBENR1_TIM4_MASK     0x00000004U
#define dRCC_APBENR1_TIM4SHIFT     2U
#define dRCC_APBENR1_TIM4EN(x)     (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR1_TIM4SHIFT)) & dRCC_APBENR1_TIM4_MASK)
#define dRCC_APBENR1_TIM6_MASK     0x00000010U
#define dRCC_APBENR1_TIM6SHIFT     4U
#define dRCC_APBENR1_TIM6EN(x)     (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR1_TIM6SHIFT)) & dRCC_APBENR1_TIM6_MASK)
#define dRCC_APBENR1_TIM7_MASK     0x00000020U
#define dRCC_APBENR1_TIM7SHIFT     5U
#define dRCC_APBENR1_TIM7EN(x)     (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR1_TIM7SHIFT)) & dRCC_APBENR1_TIM7_MASK)
#define dRCC_APBENR1_RTCAPBEN_MASK 0x00000400U
#define dRCC_APBENR1_RTCAPBENSHIFT 10U
#define dRCC_APBENR1_RTCAPBEN(x)   (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR1_RTCAPBENSHIFT)) & dRCC_APBENR1_RTCAPBEN_MASK)
#define dRCC_APBENR1_WWDGEN_MASK   0x00000800U
#define dRCC_APBENR1_WWDGENSHIFT   11U
#define dRCC_APBENR1_WWDGEN(x)     (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR1_WWDGENSHIFT)) & dRCC_APBENR1_WWDGEN_MASK)
#define dRCC_APBENR1_SPI2EN_MASK   0x00004000U
#define dRCC_APBENR1_SPI2ENSHIFT   14U
#define dRCC_APBENR1_SPI2EN(x)     (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR1_SPI2ENSHIFT)) & dRCC_APBENR1_SPI2EN_MASK)
#define dRCC_APBENR1_USART2EN_MASK 0x00020000U
#define dRCC_APBENR1_USART2ENSHIFT 17U
#define dRCC_APBENR1_USART2EN(x)   (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR1_USART2ENSHIFT)) & dRCC_APBENR1_USART2EN_MASK)
#define dRCC_APBENR1_LPUART1EN_MASK 0x00100000U
#define dRCC_APBENR1_LPUART1ENSHIFT 20U
#define dRCC_APBENR1_LPUART1EN(x)  (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR1_LPUART1ENSHIFT)) & dRCC_APBENR1_LPUART1EN_MASK)
#define dRCC_APBENR1_I2C1EN_MASK    0x00200000U
#define dRCC_APBENR1_I2C1ENSHIFT    21U
#define dRCC_APBENR1_I2C1EN(x)      (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR1_I2C1ENSHIFT)) & dRCC_APBENR1_I2C1EN_MASK)
#define dRCC_APBENR1_I2C2EN_MASK    0x00400000U
#define dRCC_APBENR1_I2C2ENSHIFT    22U
#define dRCC_APBENR1_I2C2EN(x)      (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR1_I2C2ENSHIFT)) & dRCC_APBENR1_I2C2EN_MASK)
#define dRCC_APBENR1_DBGEN_MASK     0x08000000U
#define dRCC_APBENR1_DBGENSHIFT     27U
#define dRCC_APBENR1_DBGEN(x)       (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR1_DBGENSHIFT)) & dRCC_APBENR1_DBGEN_MASK)
#define dRCC_APBENR1_PWREN_MASK     0x10000000U
#define dRCC_APBENR1_PWRENSHIFT     28U
#define dRCC_APBENR1_PWREN(x)       (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR1_PWRENSHIFT)) & dRCC_APBENR1_PWREN_MASK)
#define dRCC_APBENR1_LPTIM2EN_MASK  0x40000000U
#define dRCC_APBENR1_LPTIM2ENSHIFT  30U
#define dRCC_APBENR1_LPTIM2EN(x)    (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR1_LPTIM2ENSHIFT)) & dRCC_APBENR1_LPTIM2EN_MASK)
#define dRCC_APBENR1_LPTIM1EN_MASK  0x80000000U
#define dRCC_APBENR1_LPTIM1ENSHIFT  31U
#define dRCC_APBENR1_LPTIM1EN(x)    (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR1_LPTIM1ENSHIFT)) & dRCC_APBENR1_LPTIM1EN_MASK)

/* APB peripheral clock enable register 2 */
#define dRCC_APBENR2_SYSCFG_MASK    0x00000001U
#define dRCC_APBENR2_SYSCFGSHIFT    0U
#define dRCC_APBENR2_SYSCFGEN(x)    (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR2_SYSCFGSHIFT)) & dRCC_APBENR2_SYSCFG_MASK)
#define dRCC_APBENR2_TIM1_MASK      0x00000800U
#define dRCC_APBENR2_TIM1SHIFT      11U
#define dRCC_APBENR2_TIM1EN(x)      (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR2_TIM1SHIFT)) & dRCC_APBENR2_TIM1_MASK)
#define dRCC_APBENR2_SPI1_MASK      0x00001000U
#define dRCC_APBENR2_SPI1SHIFT      12U
#define dRCC_APBENR2_SPI1EN(x)      (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR2_SPI1SHIFT)) & dRCC_APBENR2_SPI1_MASK)
#define dRCC_APBENR2_USART1_MASK    0x00004000U
#define dRCC_APBENR2_USART1SHIFT    14U
#define dRCC_APBENR2_USART1EN(x)    (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR2_USART1SHIFT)) & dRCC_APBENR2_USART1_MASK)
#define dRCC_APBENR2_TIM14_MASK     0x00008000U
#define dRCC_APBENR2_TIM14SHIFT     15U
#define dRCC_APBENR2_TIM14EN(x)     (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR2_TIM14SHIFT)) & dRCC_APBENR2_TIM14_MASK)
#define dRCC_APBENR2_TIM16_MASK     0x00020000U
#define dRCC_APBENR2_TIM16SHIFT     17U
#define dRCC_APBENR2_TIM16EN(x)     (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR2_TIM16SHIFT)) & dRCC_APBENR2_TIM16_MASK)
#define dRCC_APBENR2_TIM17_MASK     0x00040000U
#define dRCC_APBENR2_TIM17SHIFT     18U
#define dRCC_APBENR2_TIM17EN(x)     (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR2_TIM17SHIFT)) & dRCC_APBENR2_TIM17_MASK)
#define dRCC_APBENR2_ADC_MASK       0x00100000U
#define dRCC_APBENR2_ADCSHIFT       20U
#define dRCC_APBENR2_ADCEN(x)       (((uint32_t)(((uint32_t)(x)) << dRCC_APBENR2_ADCSHIFT)) & dRCC_APBENR2_ADC_MASK)

/* IO port sleep mode clock enable register */
#define dRCC_IOPSMENR_GPIOA_MASK    0x00000001U
#define dRCC_IOPSMENR_GPIOASHIFT    0U
#define dRCC_IOPSMENR_GPIOASMEN(x)  (((uint32_t)(((uint32_t)(x)) << dRCC_IOPSMENR_GPIOASHIFT)) & dRCC_IOPSMENR_GPIOA_MASK)
#define dRCC_IOPSMENR_GPIOB_MASK    0x00000002U
#define dRCC_IOPSMENR_GPIOBSHIFT    1U
#define dRCC_IOPSMENR_GPIOBSMEN(x)  (((uint32_t)(((uint32_t)(x)) << dRCC_IOPSMENR_GPIOBSHIFT)) & dRCC_IOPSMENR_GPIOB_MASK)
#define dRCC_IOPSMENR_GPIOC_MASK    0x00000004U
#define dRCC_IOPSMENR_GPIOCSHIFT    2U
#define dRCC_IOPSMENR_GPIOCSMEN(x)  (((uint32_t)(((uint32_t)(x)) << dRCC_IOPSMENR_GPIOCSHIFT)) & dRCC_IOPSMENR_GPIOC_MASK)
#define dRCC_IOPSMENR_GPIOD_MASK    0x00000008U
#define dRCC_IOPSMENR_GPIODSHIFT    3U
#define dRCC_IOPSMENR_GPIODSMEN(x)  (((uint32_t)(((uint32_t)(x)) << dRCC_IOPSMENR_GPIODSHIFT)) & dRCC_IOPSMENR_GPIOD_MASK)
#define dRCC_IOPSMENR_GPIOF_MASK    0x00000020U
#define dRCC_IOPSMENR_GPIOFSHIFT    5U
#define dRCC_IOPSMENR_GPIOFSMEN(x)  (((uint32_t)(((uint32_t)(x)) << dRCC_IOPSMENR_GPIOFSHIFT)) & dRCC_IOPSMENR_GPIOF_MASK)

/* AHB sleep mode clock enable register */
#define dRCC_AHBSMENR_DMA1_MASK     0x00000001U
#define dRCC_AHBSMENR_DMA1SHIFT     0U
#define dRCC_AHBSMENR_DMA1SMEN(x)   (((uint32_t)(((uint32_t)(x)) << dRCC_AHBSMENR_DMA1SHIFT)) & dRCC_AHBSMENR_DMA1_MASK)
#define dRCC_AHBSMENR_DMA2_MASK     0x00000002U
#define dRCC_AHBSMENR_DMA2SHIFT     1U
#define dRCC_AHBSMENR_DMA2SMEN(x)   (((uint32_t)(((uint32_t)(x)) << dRCC_AHBSMENR_DMA2SHIFT)) & dRCC_AHBSMENR_DMA2_MASK)
#define dRCC_AHBSMENR_FLASH_MASK    0x00000100U
#define dRCC_AHBSMENR_FLASHSHIFT    8U
#define dRCC_AHBSMENR_FLASHSMEN(x)  (((uint32_t)(((uint32_t)(x)) << dRCC_AHBSMENR_FLASHSHIFT)) & dRCC_AHBSMENR_FLASH_MASK)
#define dRCC_AHBSMENR_SRAM_MASK     0x00000200U
#define dRCC_AHBSMENR_SRAMSHIFT     9U
#define dRCC_AHBSMENR_SRAMSMEN(x)   (((uint32_t)(((uint32_t)(x)) << dRCC_AHBSMENR_SRAMSHIFT)) & dRCC_AHBSMENR_SRAM_MASK)
#define dRCC_AHBSMENR_CRC_MASK      0x00001000U
#define dRCC_AHBSMENR_CRCSHIFT      12U
#define dRCC_AHBSMENR_CRCSMEN(x)    (((uint32_t)(((uint32_t)(x)) << dRCC_AHBSMENR_CRCSHIFT)) & dRCC_AHBSMENR_CRC_MASK)

/* APB sleep mode clock enable register 1 */
#define dRCC_APBSMENR1_TIM2_MASK    0x00000001U
#define dRCC_APBSMENR1_TIM2SHIFT    0U
#define dRCC_APBSMENR1_TIM2SMEN(x)  (((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR1_TIM2SHIFT)) & dRCC_APBSMENR1_TIM2_MASK)
#define dRCC_APBSMENR1_TIM3_MASK    0x00000002U
#define dRCC_APBSMENR1_TIM3SHIFT    1U
#define dRCC_APBSMENR1_TIM3SMEN(x)  (((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR1_TIM3SHIFT)) & dRCC_APBSMENR1_TIM3_MASK)
#define dRCC_APBSMENR1_RTCAPB_MASK  0x00000400U
#define dRCC_APBSMENR1_RTCAPBSHIFT  10U
#define dRCC_APBSMENR1_RTCAPBSMEN(x)(((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR1_RTCAPBSHIFT)) & dRCC_APBSMENR1_RTCAPB_MASK)
#define dRCC_APBSMENR1_WWDG_MASK    0x00000800U
#define dRCC_APBSMENR1_WWDGSHIFT    11U
#define dRCC_APBSMENR1_WWDGSMEN(x)  (((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR1_WWDGSHIFT)) & dRCC_APBSMENR1_WWDG_MASK)
#define dRCC_APBSMENR1_SPI2_MASK    0x00004000U
#define dRCC_APBSMENR1_SPI2SHIFT    14U
#define dRCC_APBSMENR1_SPI2SMEN(x)  (((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR1_SPI2SHIFT)) & dRCC_APBSMENR1_SPI2_MASK)
#define dRCC_APBSMENR1_USART2_MASK  0x00020000U
#define dRCC_APBSMENR1_USART2SHIFT  17U
#define dRCC_APBSMENR1_USART2SMEN(x)(((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR1_USART2SHIFT)) & dRCC_APBSMENR1_USART2_MASK)
#define dRCC_APBSMENR1_LPUART1_MASK 0x00100000U
#define dRCC_APBSMENR1_LPUART1SHIFT 20U
#define dRCC_APBSMENR1_LPUART1SMEN(x)(((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR1_LPUART1SHIFT)) & dRCC_APBSMENR1_LPUART1_MASK)
#define dRCC_APBSMENR1_I2C1_MASK    0x00200000U
#define dRCC_APBSMENR1_I2C1SHIFT    21U
#define dRCC_APBSMENR1_I2C1SMEN(x)  (((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR1_I2C1SHIFT)) & dRCC_APBSMENR1_I2C1_MASK)
#define dRCC_APBSMENR1_I2C2_MASK    0x00400000U
#define dRCC_APBSMENR1_I2C2SHIFT    22U
#define dRCC_APBSMENR1_I2C2SMEN(x)  (((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR1_I2C2SHIFT)) & dRCC_APBSMENR1_I2C2_MASK)
#define dRCC_APBSMENR1_DBG_MASK     0x08000000U
#define dRCC_APBSMENR1_DBGSHIFT     27U
#define dRCC_APBSMENR1_DBGSMEN(x)   (((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR1_DBGSHIFT)) & dRCC_APBSMENR1_DBG_MASK)
#define dRCC_APBSMENR1_PWR_MASK     0x10000000U
#define dRCC_APBSMENR1_PWRESHIFT    28U
#define dRCC_APBSMENR1_PWRSMEN(x)   (((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR1_PWRESHIFT)) & dRCC_APBSMENR1_PWR_MASK)
#define dRCC_APBSMENR1_LPTIM2_MASK  0x40000000U
#define dRCC_APBSMENR1_LPTIM2SHIFT  30U
#define dRCC_APBSMENR1_LPTIM2SMEN(x)(((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR1_LPTIM2SHIFT)) & dRCC_APBSMENR1_LPTIM2_MASK)
#define dRCC_APBSMENR1_LPTIM1_MASK  0x80000000U
#define dRCC_APBSMENR1_LPTIM1SHIFT  31U
#define dRCC_APBSMENR1_LPTIM1SMEN(x)(((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR1_LPTIM1SHIFT)) & dRCC_APBSMENR1_LPTIM1_MASK)

/* APB sleep mode clock enable register 2 */
#define dRCC_APBSMENR2_SYSCFG_MASK  0x00000001U
#define dRCC_APBSMENR2_SYSCFGSHIFT  0U
#define dRCC_APBSMENR2_SYSCFGSMEN(x)(((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR2_SYSCFGSHIFT)) & dRCC_APBSMENR2_SYSCFG_MASK)
#define dRCC_APBSMENR2_TIM1_MASK    0x00000800U
#define dRCC_APBSMENR2_TIM1SHIFT    11U
#define dRCC_APBSMENR2_TIM1SMEN(x)  (((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR2_TIM1SHIFT)) & dRCC_APBSMENR2_TIM1_MASK)
#define dRCC_APBSMENR2_SPI1_MASK    0x00001000U
#define dRCC_APBSMENR2_SPI1SHIFT    12U
#define dRCC_APBSMENR2_SPI1SMEN(x)  (((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR2_SPI1SHIFT)) & dRCC_APBSMENR2_SPI1_MASK)
#define dRCC_APBSMENR2_USART1_MASK  0x00004000U
#define dRCC_APBSMENR2_USART1SHIFT  14U
#define dRCC_APBSMENR2_USART1SMEN(x)(((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR2_USART1SHIFT)) & dRCC_APBSMENR2_USART1_MASK)
#define dRCC_APBSMENR2_TIM14_MASK   0x00008000U
#define dRCC_APBSMENR2_TIM14SHIFT   15U
#define dRCC_APBSMENR2_TIM14SMEN(x) (((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR2_TIM14SHIFT)) & dRCC_APBSMENR2_TIM14_MASK)
#define dRCC_APBSMENR2_TIM16_MASK   0x00020000U
#define dRCC_APBSMENR2_TIM16SHIFT   17U
#define dRCC_APBSMENR2_TIM16SMEN(x) (((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR2_TIM16SHIFT)) & dRCC_APBSMENR2_TIM16_MASK)
#define dRCC_APBSMENR2_TIM17_MASK   0x00040000U
#define dRCC_APBSMENR2_TIM17SHIFT   18U
#define dRCC_APBSMENR2_TIM17SMEN(x) (((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR2_TIM17SHIFT)) & dRCC_APBSMENR2_TIM17_MASK)
#define dRCC_APBSMENR2_ADC_MASK     0x00100000U
#define dRCC_APBSMENR2_ADCSHIFT    20U
#define dRCC_APBSMENR2_ADCSMEN(x)   (((uint32_t)(((uint32_t)(x)) << dRCC_APBSMENR2_ADCSHIFT)) & dRCC_APBSMENR2_ADC_MASK)


/**
 * @brief Initialize RCC (Reset and Clock Control module)
 * @note  Configures:
 *        - HSE oscillator
 *        - HSI calibration
 *        - PLL configuration
 *        - System clocks (HCLK, APB1)
 *        - Peripheral clocks
 *        - Sleep mode clocks
 * @retval None
 */
void RCC_Init(void);

/**
 * @brief RCC oscillator callback
 * @retval None
 */
void cbRCC(void);
